name: Build VPN lists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python build_sub.py

      - name: Commit
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"

          git add full.txt
          git add best.txt

          git diff --cached --quiet && exit 0

          git commit -m "update lists"
          git push
